version: '3.8'

services:
  geo:
    build: .
    container_name: geo
    #ports:
    #  - "8080:8080"
    depends_on:
      - prometheus
      - grafana
    restart: unless-stopped
    networks:
      - geo-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    #ports:
    #  - "9090:9090"
    networks:
      - geo-network

  grafana:
    image: grafana/grafana
   # ports:
   #   - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - geo-network

networks:
  geo-network:

volumes:
  grafana-storage:
  prometheus-data:
