###
POST localhost:8080/api/address/geocode
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXNoa2EifQ.7Sk713PBDcxfuQFBM5Ruqao-uF9mMgMtHaVHgdNuWvg

{
  "lat": "60.1282",
  "lng": "18.6435"
}