version: '3'

services:
  proxy:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - hugo

  hugo:
    image: klakegg/hugo:0.92.2
    ports:
      - "1313:1313"
    command: "server --bind=0.0.0.0"

