version: '3.8'

services:
  library-server:
    build: .
    container_name: library-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ./library-server
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: library-server-db

volumes:
  postgres-data:
