version: '3.8'

services:
  geo-service:
    build: .
    container_name: geo-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    #command: go tool pprof ./cmd/main.go http://host.docker.internal:8080/debug/pprof/profile
    restart: unless-stopped
    networks:
      - geo-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres
      POSTGRES_DB: geo-service-db
    restart: unless-stopped
    networks:
      - geo-network

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - geo-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  geo-network:

volumes:
  postgres-data:
  grafana-storage:


